// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2un5EEZQKScFmuJDHnp80f7C6yr2fQEw',
    appId: '1:391763527916:web:9c7a69f979ab00f4c53dc9',
    messagingSenderId: '391763527916',
    projectId: 'lifeboard-8cd26',
    authDomain: 'lifeboard-8cd26.firebaseapp.com',
    storageBucket: 'lifeboard-8cd26.firebasestorage.app',
    measurementId: 'G-LYX9GSWGV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR3FOXaHSLDBoeJHc6GtEbmb4qQOmJoAY',
    appId: '1:391763527916:android:d9c9664bcfe3dddbc53dc9',
    messagingSenderId: '391763527916',
    projectId: 'lifeboard-8cd26',
    storageBucket: 'lifeboard-8cd26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPtF8-e-4bJnS1aYIVPVJSiKcJutHDILU',
    appId: '1:391763527916:ios:42c105b45df89f6fc53dc9',
    messagingSenderId: '391763527916',
    projectId: 'lifeboard-8cd26',
    storageBucket: 'lifeboard-8cd26.firebasestorage.app',
    iosBundleId: 'com.lifeboard.lifeboard',
  );
}
